services:
  web:
    build:
      context: .
    command: npm run dev -- --host
    develop:
      watch:
        - action: sync
          path: src
          target: /usr/src/app/src
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
    ports:
      - 5173:5173
